services:

  postgres:

    image: postgres:15

    container_name: fraud-postgres

    environment:
      POSTGRES_USER: fraud_user
      POSTGRES_PASSWORD: fraud_password
      POSTGRES_DB: fraud_detection

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  api:

    build: .

    container_name: fraud-api

    depends_on:
      - postgres

    env_file:
      - .env

    ports:
      - "8000:8000"

volumes:
  postgres_data: